---
title             : "To be FAIR: Theory Specification Needs an Update"
authors           : "Caspar van Lissa on behalf of co-authors"
journal           : "Perspectives on Psychological Science"
handling_editor   : "Vrieze"
class             : "draft"
bibliography      : "fair_theory.bib"
output            : revise::revise_letter_pdf
---

Dear Dr `r rmarkdown::metadata$handling_editor`,

Thank you for considering our manuscript for publication at _`r rmarkdown::metadata$journal`_.
We appreciate the feedback that you and the reviewers have provided.
In this action letter, we respond to each comment point by point.

```{r setup-chunk, include = FALSE}
library(revise)
rm(".revise_manuscripts")
revise::read_manuscript("abstract.md")
revise::read_manuscript("test.Rmd")
```


## Editor's Comments

```{asis}
Thank you for submitting Manuscript ID PPS-25-140 entitled "To be FAIR: Theory Specification Needs an Update" to Perspectives on Psychological Science. It now has been reviewed.  The comments of the reviewer(s) are included at the bottom of this letter.

The reviewer(s) have recommended publication, but also suggest some revisions to your manuscript. I have some further comments, which I hope also will be helpful to you in making a revision. Therefore, I invite you to respond to the reviewer(s)' and my comments and to revise your manuscript.

[x] Headings should not be numbered.
[x] Tables and Figures should be uploaded separately and not positioned in the text (although it is fine to indicate where they should be inserted).
[] Figures should be uploaded in their native format (the program they were created in) at 300 dpi. Acceptable figure file formats include MS Office files (DOC, PPT, XLS), Adobe Illustrator (AI), JPG, EPS, and PDF.
[x] References should be done with hanging indents using APA style. 
[] If you want to add the doi that is good.  But do not put in the search criteria for retrieving a document that has been published in a book or journal. WHAT??
```

We have 
Upload tables separately: tab_meehl.csv
Upload figures separately: ec_visio.pdf, git_branches.png, git_compare_short.png


```{asis}
a) You have a balancing act to strike between providing technical tools (e.g., version control workflows) that can assist scientists in implementing your proposals on the one hand, against a readership and a scientific discipline that likely largely cannot effectively implement such tools. I will give a simple example. The very first thing I read after the title page was "This is a preprint paper, generated from Git Commit # 7b710ba5." I wager that most readers of Perspectives do not know what a git commit is, at least not in any meaningful way. This is a minor example, but illustrates the larger point. Reviewer 2 (Turkheimer) makes this point in his review.
```

We understand that striking the balance between the conceptual and technical details is the very challenge of this paper. In the revision we have tried to explain technical details in even simpler language.
The most important change we have made, as requested by Reviewer #2, is to move the tutorial parts of the paper into package vignettes.
We still leave a conceptual overview of the tutorial in simpler language because we do want readers of the paper to come away with some idea of what making a theory FAIR entails, and because these general principles are not tied to the R-pacakge and our specific implementation (they could be implemented using other infrastructures).

With regard to your specific example of technical language that might elude the readership, the GitHub reference in the author note now reads: "Our manuscript is reproducible given the code provided in our Github repository identified by the snapshot with the unique commit id #XXXXX." 

```{asis}
b) My interpretation of this manuscript is that it is proposing policies, procedures, and documentation as an important path forward to improve psychology and related soft sciences. One reason I find such proposals interesting is because I don't see them in my other area of expertise, human genetics. No doubt strong conventions develop in genetics, but they seem to develop because scientists writ large working in those fields recognize that those conventions (e.g., publicly available genomic maps organized in a certain way; analytical workflows based on accepted genetic theories) will immediately benefit their own area of research by making new avenues of work feasible, or more efficient. The payoff is obvious. They are "no-brainers" that organically arise. Some conventions in psychology, like registration or even data sharing, do not seem to arise or take hold in quite the same way, and instead rely on top-down requirements by grant funding agencies, journals, etc. 

I can definitely see the advantage to policies, procedures, and documentation, if the goal is to identify fraudulent work, because it creates a paper trail to audit. I am more skeptical that these things are crucial to scientific advance in psychology, and there are no empirical results in this paper to the contrary. I believe this echoes Reviewer 3's suggestion to take seriously in your discussion, and I would suggest elsewhere in the paper, the limitations of policies, procedures, and documentation, versus other aspects of the scientific enterprise including culture, norms, and perhaps even the tractability of the subject matter, as in my human genetics example. 
```

<!-- Make comparison to preregistration; that was first proposed and only later evaluated. -->
<!-- Mention how few of preregistered hypotheses are true, and yet how theory is rarely updated? Thus, falsificationism is not working in practice. -->

<!-- <!-- AB: --> -->
<!-- 2.	I think the policies argument is interesting. I agree that currently we simply claim that establish FAIR theories will profit the advancement of science by an argument of analogy (to open data and open code) but ultimately we do not know. For one, I think it's fair to admit this. Second, I would argue that FAIR theories is not a very strict policy (in contrast to other stances in science, which require very specific ways of working, e.g. commiting to falsificationism, adhering to ethical principles, etc.). Really, FAIR theories are no restriction in that sense but more of a protocol for communication, which ultimately does not change your workflow or your methods. -->

We appreciate the Editor’s meta-scientific comparison of the emergence of conventions in human genetics to the (current wave of) more top-down nature of open science reforms in psychology, which by-and-large also originated in grass-roots initiatives.

To clarify our perspective: As methodologists, our focus is on "procedures", rather than policies or documentation. Our goal in this paper is to position FAIR theory as a set of standards, grounded in philosophy of science and implemented in existing infrastructure, that facilitates theory specification, reuse, and collaborative refinement.

We agree with the Editor that there is no guarantee that *"these things are crucial to scientific advance in psychology"*. We have, however, provided reasoned arguments to support the "affordances" of FAIR theory: it *makes possible* particular scientific advancements, even if it does not guarantee them.

Compare FAIR theory to preregistration: it, too, was introduced first as a good idea.
Only now - a decade later - are empirical studies are being conducted to investigate its effects.on scientific practices.

To address this comment, <font color="red">in the Revision:

* We explicitly state that we describe the affordances of FAIR theory and argue for its potential impact by comparing it to other open science methods
* We acknowledge in the Limitations section that empirical evidence for these potential benefits remains to be evaluated.

</font>

<!-- However, our paper is a different kind of paper than an empirical study: we provide a reasoned argument to justify FAIR theory, based on philosophy of science   -->

<!--  Unlike more prescriptive norms—such as commitments to falsificationism or methodological registration—FAIR theory does not constrain a researcher’s workflow or analytical choices. It simply makes theoretical assumptions transparent, findable, and versioned. This distinction is important: the goal is not to impose rigid procedures, but to enable a more cumulative and accountable theoretical discourse. Still, we agree with the reviewer that policies and infrastructure alone are insufficient to drive meaningful change. Culture, norms, and the nature of the subject matter all shape how—and whether—reforms take root. In that spirit, we see FAIR theory not as a top-down imposition, but as a bottom-up opportunity: it offers immediate utility to researchers who want their theories to be discoverable, citable, and improvable. Over time, its adoption may well depend not on mandates, but on whether it proves valuable enough to become a “no-brainer” for the psychological sciences as it has in fields like genetics. -->


## Reviewer: 1


```{asis}
In this manuscript, the authors introduce a framework for FAIR theory specification while outlining what makes a theory FAIR, which is accompanied by practical guidance on how to implement this in one’s own work. In my opinion, the paper is relevant for the journal and presents research that is significant for the field of psychology but also adjacent fields that rely on theories similar in nature to ours. FAIR theory is a promising idea that could significantly advance psychological research, especially in terms of transparency and replicability.
```

We thank the Reviewer for their thoughtful and encouraging review.
We appreciate the Reviewer's recognition of the relevance and potential impact of FAIR theory—not only within psychology, but also in related disciplines.
We have sought to address all comments, and feel that doing so has improved the quality of the manuscript.

```{asis}
The abstract provides a (mostly) comprehensive overview of the paper that can be easily followed and understood. I personally felt that the introduction of the theorytools R-package was an important aspect of the paper and should thus briefly be mentioned in the abstract.
```

As suggested, we now briefly mention the R-package in the abstract:

`r get_revision("abstractpackage")`

```{asis}
In the abstract, the authors mention the discussion of “FAIR theories’ potential impact in terms of reducing research waste,” which I couldn’t really find at any point in the manuscript.
```

We thank the Reviewer for pointing this out; we have included the reference to the paper making this argument in the following section:

`r get_revision("waste")`

```{asis}
Lines 48–50: I would have benefited from a few more words on the FAIR guiding principles (what they are, where/how they originated, and how they are used).
```

As requested, we have added a few more words - but we also want to avoid redundancy, as the FAIR principles are fairly (pun intended) common sense, and well-documented in other publications which are all cited in the opening paragraph. In the body of the text, we explicitly engage with each of the FAIR (sub-) principles, so all information is already contained within the paper.

To address the comment, we have rewritten the opening paragraph as follows:

`r get_revision("whatsfair")`


```{asis}
Line 101: In Figure 1a, it would be helpful to see the two phases (currently, those are not clear to me). Also, even though Figure 1c is addressed at a much later point in the manuscript, it would be helpful to briefly mention it here as well, so it doesn’t seem forgotten.
```

**DO THIS**

```{asis}
Line 102: The corresponding year should be added to “Wagenmakers and colleagues.”
```

Done.


```{asis}
Line 147: In the case of “Lamprecht and colleagues,” the year should also be added.
```

Done.

```{asis}
In general, I’d move this section up, as the word “theory” has been used a lot already at this point, and readers might benefit from an earlier explanation/definition (for example, directly after the section “The Need for FAIR Theory”).
```

We have done as requested, and additionally, include a sentence in the first paragraph to pre-emptively address readers' concerns that FAIR theory may only be relevant for those who have adopted a specific paradigm:

`r get_revision("alldefinitions")`

```{asis}
Line 163: Following APA 7 standards, no “cf.” is added. In the case of three or more authors, it is shortened to “et al.”
```

We removed "cf." here, although we couldn't find mention of it in the APA7 style guide.
We use "cf." to indicate when a specific reference *contradicts* a point; e.g. "all theories should be formal (Smaldino, 2017; cf. Oude-Maatman, 2024)": Oude-Maatman disagrees with this statement.
We have also updated the citation scheme to APA7, so three or more authors will be shortened to "et al.".
Note that some journals prescribe citation styles that (partly) conflict with APA7; we defer to the Editor on how to handle such cases.

```{asis}
Line 207: It could be helpful to add a very brief description of the phonological loop in case some readers are not familiar with it and its parameters.
```

**DO THIS, ANDREAS?**

```{asis}
Line 350: I think that this was supposed to be displayed as a link: <www.theorymaps.org>
```

Thank you for pointing this out; we have fixed the formatting.

```{asis}
Line 390: In the case of a direct quotation, a page number should be added if possible.
```

We have added the page numbers to all direct quotations.

```{asis}
Line 688: I’d add the year for Van Lissa’s specification.
```

Done.

```{asis}
Line 776 onwards: The proposed system of modular publishing seems to have been around for quite some time (since 1998 at least) but is not widely used, which could briefly be addressed as a limitation.
```

We respectfully disagree; open data - one example of modular publishing - has increased dramatically in recent decades, in psychology the percentage of articles that share data has increased from ~7% in 2000–2009 to ~50% in 2010-2019. In other disciplines, the increase has been even larger (up to ~80%).
Given this, we don't see a reason to note this as a limitation, but we have added a reference that indicates that data sharing has become widely adopted in psychology:

`r get_revision("datasharing")`

```{asis}
Line 800: To make the strengths understandable to all readers, I’d encourage the authors to briefly explain the “open empirical cycle.”
Overall, this is a very “strong” section indeed!
```

We have rewritten this section slightly, including a brief explanation of the "open empirical cycle" and how the present work relates to it:

`r get_revision("openec")`

```{asis}
In my opinion, it is very important that the learning curve is mentioned; even though I am a big fan of the proposed framework in general, I do feel like it would take some practice and getting used to.
```

We had mentioned the learning curve in the Limitations section, and have expanded this discussion to address the present comment:

`r get_revision("learningcurve")`

```{asis}
Line 852: I’d add a reference for the jingle-jangle fallacy.
```

We have done as requested; this section now reads:

`r get_revision("jinglejangle")`


```{asis}
The affiliations could be changed to follow a common system.
```

We have tried to make this requested change, although there is some residual heterogeneity because our institutions have different preferred / mandated ways to write the affiliation.

```{asis}
I do understand why the words Findable, Accessible, Interoperable, and Reusable are always written with a majuscule, but it did confuse me a bit during reading at times.
```

Since all of these words have a colloquial meaning in everyday language, as well as a more restrictive operationalization in the literature on the FAIR principles, we think its important to signal the distinction between the formal and colloquial use of the terms. We now clarify this in a footnote, the first time the capitalized terms are introduced:

`r revise::get_revision("faircap")`

```{asis}
The references should use sentence case following APA 7 (e.g., Back to Basics: The Importance of Conceptual Clarification in Psychological Science → Back to basics: The importance of conceptual clarification in psychological science).
```

We've updated the reference style to APA7, but note that some journals have fixed the case of specific words in titles (e.g., "FAIR" is fixed to capital letters). These remain unchanged. We defer to the Editor to indicate whether we should change this, or whether it will be addressed in the typesetting process.

```{asis}
I’ve mentioned these two already for specific examples, but I’d check them in the whole manuscript again: In the case of more than two authors, use of et al. and the mention of page numbers for direct quotations.
```

Done.

```{asis}
Two of the links did not work for me: Line 490 (FAIR metadata example), Line 606 (example of metadata).
```

We apologize for the oversight, and have fixed these hyperlinks.

## Reviewer: 2

```{asis}
I submit this review signed as Eric Turkheimer. 

Editors generally prefer that reviewers not preface their reviews with declarations of their lack of expertise in the relevant subjects, but I am going to allow myself to do so here, because I already said as much to the editor when I was asked to review the paper. I have no particular expertise in meta-science; I have never (I am somewhat embarrassed to admit) so much as pre-registered an analysis. I am 71, and open science procedures are the blinking 12:00 on my VCR.

I am here as a practitioner of theory, not as a meta-theorist. I have written a few "theoretical" papers over the years, of different kinds that I will get to in a minute.  I want to consider how adopting a FAIR framework would change, improve, or inhibit what I do.

I can think of two kinds of theoretical papers I have written, or perhaps better, two theoretical research programs I have participated in.  One of them is closely tied to empirical results. I am thinking of the Scarr-Rowe hypothesis, something that was developed by Sandra Scarr and David Rowe, and then turned into something resembling a theory by our 2003 paper.   Since then it has been much investigated and argued about.

In this case, I think the FAIR framework would be very helpful. The S-R hypothesis makes a number of empirical claims with respect to theory. These claims have changed in response to empirical results and theoretical disputes over the years.  I have often been frustrated by the difficulty of maintaining meaningful boundaries on the theory and the predictions it makes.

Here are two examples. In the months after our paper was published, someone (Nagoshi, C. T., & Johnson, R. C. (2005). Socioeconomic status does not moderate the familiality of cognitive abilities in the Hawaii Family Study of Cognition. Journal of Biosocial Science, 37(6), 773-781.) shot out a "failure to replicate." But it wasn't-- their analysis studied parent-child correlations, not twins, and the S-R hypothesis makes no predictions about them. But despite 20 years of trying to make this clear in the published literature, the study is still cited. An even worse example happened recently, when a group of "race scientists" (Pesta, B. J., Kirkegaard, E. O., te Nijenhuis, J., Lasker, J., & Fuerst, J. G. (2020). Racial and ethnic group differences in the heritability of intelligence: A systematic review and meta-analysis. Intelligence, 78, 101408.) used the S-R hypothesis as a platform for a bunch of unrelated claims about race differences.

To be clear, it cuts both ways. It has turned out over the years that the S-R interaction does not occur in Europe, and I have revised the theory to fit the new facts, but I have done so on a strictly ad hoc basis. It would be easy to suggest that I am adding epicycles to it, and having a formalized structure for the theoretic revisions would help keep me honest.  Similarly, when conducting new analyses, I am often confronted with investigator degrees of freedom (should we use parental education or income as an SES indicator) that are very difficult to resolve in the privacy of the lab.  Having a structured platform for doing so would help.
```

Dear prof. Turkheimer,

on behalf of all co-authors, let me express our sincere appreciation for your thoughtful comments. This is my (Caspar's) favorite review to date, and I especially value your perspective as a seasoned scholar/theoretician. We have attempted to address your comments in the Revision, as described below. In addition, all authors agreed that it would be a pity to deprive our readers of an opportunity to view FAIR theory through the lens of your lived experience - but we were not entirely sure how to incorporate it. We invite your, and the Editor's, advice on how to best go about it.

As a starting point, we drafted a paragraph that summarizes your comments on FAIR theory from the review, and mentioned your contribution in the Acknowledgements. We are open to incorporating your thoughts and crediting your contribution in other ways as well, depending on what seems appropriate to you and the Editor.

Our draft paragraph now reads:

`r get_revision("turkheimer")`

The Acknowledgement now reads:

> We are particularly endebted to our Reviewer, Dr. Eric Turkheimer, whose thoughtful reflections on FAIR theory were incorporated into the Discussion.

```{asis}
(This sounds like pre-registration. I don't think there is a bright line between FAIR theorizing and preregistering.)
```

We respectfully disagree that FAIR theory is like preregistration, and we think that this comment signals a need to better explain the important distinctions between these two practices.
To address this comment, we have included the following section in the revision:

`r get_revision("fairtheoryprereg")`

```{asis}
The second kind of theorizing I have done is more philosophical, along the lines of my "Three Laws" paper and related work. Here, I think applying the FAIR framework would be a little more problematic. At times, the current manuscript sounds as though it is trying to make scientific theory machine readable, an idea that has some good points that the authors make clear, but would also eliminate a lot of interesting papers that have been written by human beings from a subjective point of view. What would happen to Meehl's great Sir Karl Sir Ronald paper within FAIR? How much of the importance of that paper would remain if you took Meehl's voice out of it? Is all narrative philosophy "theorizing" that could be augmented or replaced by FAIR? See also: Meehl on "Cliometric metatheory".

These considerations lead me to some recommendations for strengthening the manuscript. The first is to clarify the relationship between FAIR theory and traditional paper-writing. Is the former meant to replace or enhance the latter? It seems to me that using FAIR to enhance the environment created by traditional theoretical papers is much the better option.  That is, everything that currently exists about the S-R hypothesis could continue to exist, and be supplemented by a FAIR framework outlining the theory and its implications. Development of the FAIR model could exist almost independently of the individual papers, analyses, reviews and meta-analyses (see below). Someone could contribute to the literature on a subject by developing a FAIR framework, much as a good review paper does.
```

We agree, this is exactly how we envision the role of FAIR theory. We think this comment can be concisely addressed by emphasizing that modular publishing does not replace the traditional paper, but adds value to resources created in the process of its writing:

`r get_revision("modularvalue")`

And:

`r get_revision("modularpublisingdetract")`

```{asis}
Second, and speaking of Meehl, many of the ideas incorporated here have a relationship to construct validity.  Many of our "theories" of behavior take the form of hypothetical constructs, like intelligence or for that matter the S-R interaction. Much of what is described here seems like a formalization of Meehl's idea of a nomological net-- a network of theoretical connections among abstract entities and empirical observations.
```

We partly agree; we recognize two distinct lines of thought in this comment. 

The first is that FAIR theory relates to construct validity. To address this point, we have rewritten the section on FAIR theory and the "measurement crisis":

`r get_revision("measurementcrisis")`

The second is that much of what we describe looks like Meehl's nomological nets. This is definitely true for the way that *we* are using FAIR theory (e.g., in the online examples), as we are inspired by Meehl,
but it's not necessarily true of FAIR theory in general. 
We agree that several psychological theories can be specified as a nomological network of abstract entities and empirical predictions/observations.
However, not all theories have been specified to such a level or need to be specified in such a way. 
As such, FAIR Theory accommodates nomological nets and construct validation endeavours, but is not identical to them. 
It is interesting to note that Cronbach and Meehl (1955) did talk about (proto)FAIR requirements:
"Whether or not an interpretation of a test’s properties or relations involves questions of construct validity is to be decided by examining the entire body of evidence offered, together with what is asserted about the test in the context of this evidence." (p.4)
"Hence, the investigator who proposes to establish a test as a measure of a construct must specify his network or theory sufficiently clearly that others can accept or reject it." (p.13)
"A consumer of the test who rejects the author’s theory cannot accept the author’s validation. He must validate the test for himself, if he wishes to show that it represents the construct as he defines it."
We're not sure if further changes need to be made to address this.

```{asis}
Finally, and this is the only concern about the paper as a publishable manuscript, the last third of the paper where the authors get into the technical aspects of how one would go about building a FAIR theory, is difficult to read. This is where the manuscript reads more like a software manual than a perspectives paper. It would seem out of place in this journal, and frankly it left me discouraged about the prospect of trying this on my own. In its place, I would recommend working an example for an actual theory, with as much of the specific detail as possible removed from the main text.
```

To address this comment, we have removed as much of the specific detail as possible from the main text, relegating it to the package vignettes instead.
To make this possible, we have substantially expanded the existing package vignettes and created one additional vignette.

There are now three worked examples for actual theories in the package vignettes:

* [Self-Determination Theory](https://cjvanlissa.github.io/theorytools/articles/formalizing_sdt.html)
* The [Dunning-Kruger Effect](https://cjvanlissa.github.io/theorytools/articles/dunning-kruger.html)
* [Morris' Tripartite Model](https://cjvanlissa.github.io/theorytools/articles/causal-inference.html)

The resulting shortened section reads as follows:

`r get_revision("tutorial")`


## Reviewer: 3

```{asis}
I have read through the manuscript on FAIR theories in psychology. I am extremely sympathetic with the arguments in the paper and believe it will make a valuable contribution.

Drawing on previous work on FAIR principles, the authors of this manuscript argue that psychological theories should be findable, accessible, interoperable, and reusable. These principles are clearly part of a broad movement toward improved and open science in disciplines like psychology.

The authors point out that, despite many reforms since the identification of the "replication crisis" meant to improve scientific rigor (e.g. per-registration), the problems lie with deeper root causes, including a problem with theory development. I could not agree more. For example, there is often little connection between theory and hypotheses. In addition, theories are often so ambiguous as to be unfalsifiable. The key issue, according to the authors, lies in where we should focus reform efforts. To date, reform efforts have focused on improving deductive methods, while overlooking the process of theory construction and improvement. I completely agree.

In the rest of the paper, the authors lay out specific aspects of their argument (e.g. what is a theory? what is the role of formalization in theory development? what is modular publishing? what role should version control play in theory development? etc.). They then discuss a specific example of how to implement the FAIR principles in theory construction and development.

As should be obvious, I am a fan of this paper.
```

We are grateful for this thoughtful and supportive review.
The Reviewer's clear articulation of the central goals of our paper, and their agreement with the need to (re)focus reform efforts on theory development, is affirming and encouraging.

```{asis}
That said, I wonder if the paper could be improved with a more probing discussion section. If I had one criticism of the paper, I would say that it lets scientists off the hook too easily. An uncritical reader might conclude that the issue is merely one of creating the right set of norms (e.g. version control through Git and archiving through Zenodo). I am doubtful. The sciences (especially physics) have not run into the same problems as psychology and yet they have not always nor always currently practice anything like these FAIR practices. Sure, physics tends to use formal theory, which limits some of the most egregious issues associated with the replication crisis. But that is not true of most theory in biology --- and yet biology has done a better of job of good theory development. I wonder if the authors would be willing to talk more in the discussion about the role of values? We live in a world that is dominated by the logic of incentives: If we just get the incentives right, then we can solve all of our problem. Perhaps. This logic suggests scientists are motivated by mere self-interest (why else would we need the incentives?) and operate in a world of ignorance (e.g. scientists are not aware that their theories are vague and why that is bad for science). I accept that both of these are true, to a large degree. If so, I worry that creating new incentives may only exacerbate problems. It seems to me that we need a change in values. For example, scientists should be embarrassed by publishing vague and ambiguous theories---at least after that has been pointed out to them. I am not trying to be a scold here, but I wonder if there's value in talking about how we might better cultivate norms and values in scientists without requiring more procedures and incentives. After all, why have the problems in the social sciences not so badly infected the sciences? The authors address these issues to some degree (e.g. they mention that they are often asked "who owns a theory?" during seminars. This is precisely the problem! That that question would be asked suggests a deeper problem than incentives---the problem lies in not really understanding what science is or how it works.

Sorry for the rant! I really loved the paper and think it is fine as is. I would love to see a bit more of a discussion about issues like values, but I don't need to see that.
```

We appreciate this thought-provoking comment, which explores the broader sociological and cultural dimensions of scientific reform.
We are sympathetic to the reviewer’s view that the challenges facing psychology are not solely technical or procedural, but likely also reflect deeper issues of norms and values.

That said, we are not sure that we are best positioned to engage with these issues, nor that the present paper would be the best place for such an argument.
As methodologists, our primary aim in this paper is to articulate the affordances of FAIR theory:
a framework that supports better theory specification, sharing, and reuse.
We believe we can make this contribution most effectively if we remain sharply focused on the practical infrastructure and its scientific use cases.

We do not mean to suggest that infrastructure alone is sufficient, nor do we discount the importance of cultivating scientific values.
However, we believe that meta-scientists and sociologists of science would be better positioned to engage with the topics of norms and values,
and that these topics are better suited to empirical enquiry - i.e., establishing what the most widely held norms and values are, and how these relate to endorsements of academic practices.

We share the Reviewer's interest in the meta-scientific perspective,
and we hope that the Reviewer will agree that - while there is clearly a need for enquiry into norms and values - the present paper might not be the best avenue for it.

We did make one minor change to address this comment, and "punched up" the section on Theory and Scientific Progress, with a reference to scientific norms as documented in ethical guidelines:

`r get_revision("norms")`

\clearpage

# References {-}

::: {#refs custom-style="Bibliography"}
:::

